version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        exclude-patterns:
          - "tools.jackson*"
          - "org.slf4j*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dev-dependencies"
