version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      day: 25
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: 25
    labels:
      - "dev-dependencies"
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
