[configuration]
== Configuration

There are two main classes when using WebAuthn4J. One is `WebAuthnRegistrationContextValidator` class, which is
used to verify the credentials at the time of registration, and the other is `WebAuthnAuthenticationContextValidator` class,
which is used to verify the credentials during authentication.

`WebAuthnRegistrationContextValidator` delegates attestation statements validation to an implementation of
`AttestationStatementValidator` and attestation statements trustworthiness validation to an implementation of
`CertPathTrustworthinessValidator`.

Since most sites don't require strict attestation statement validation
(https://www.w3.org/TR/webauthn-1/#sctn-no-attestation-security-attestation[WebAuthn Spec related topic] ),
WebAuthn4J provides `WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` factory method
that returns an instance configured `CertPathTrustworthinessValidator` and  `WebAuthnRegistrationContextValidator`
not to validate attestation statements.

If you are engaging an enterprise use case and strict verification of an authenticator is a requirement,
Use the constructor of the `WebAuthnRegistrationContextValidator` class and inject validators.

=== Attestation statement validation

Attestation statement validation is provided by the implementation of `AttestationStatementValidator` interface.
For each attestation statement format, corresponding validator classes are provided.
Please specify its list at the first argument of the constructor of `WebAuthnRegistrationContextValidator` class.
For example, if you would like to limit the supported format to `packed` only, make the `List` only with
`PackedAttestationStatementValidator`, and if you would like to support `packed` and `tpm` format, make the `List` with
`PackedAttestationStatementValidator` and `TPMAttestationStatementValidator`.

==== Attestation statement trustworthiness validation

Attestation statement trustworthiness validation has three patterns: certificate path validation, ecdaa validation, and
self attestation.
Certificate path validation is delegated via `CertPathTrustworthinessValidator` interface, and ECDAA is delegated via
`ECDAATrustworthinessValidator` interface. WebAuthn4J provides some `CertPathTrustworthinessValidator` implementations.
For example, `TrustAnchorCertPathTrustworthinessValidator` verifies trustworthiness by checking the attestation certificate
chains to the root certificate provided as `TrustAnchor` via `TrustAnchorResolver` interface.

===== Attestation statement trustworthiness validation using FIDO Metadata Service

FIDO Alliance offers FIDO Metadata Service, which delivers Authenticator metadata.
With this service, Relying Party can judge whether a security issue is reported for the authenticator trying to register.
When verifying the reliability of the attestation statement with this service, `MetadataItemsCertPathTrustworthinessValidator` in
`webauthn4j-metadata` module can be used for it.
As `MetadataItemsCertPathTrustworthinessValidator` resolves the `MetadataItem` list corresponding to
the AAGUID of the authenticator through the `MetadataItemsResolver` interface, we can verify the reliability with
the service by a combination of `MetadataItemsResolverImpl` and `FidoMdsMetadataItemsProvider`.

=== Representation of an authenticator

WebAuthn4j provides `Authenticator` interface as a representation of an authenticator.

On registering the authenticator, you need to persist its representation by creating the instance implementing
`Authenticator` interface in your application manner because it is used afterwards on authentication verification.
It might be better to use credentialId as a search key for this persisted instance.

You can freely enhance the class implementing `Authenticator` interface in order to meet your application’s requirements.
For example, you can add the field for your application’s user to identify the authenticator.


