== Configuration

WebAuthn4J has a one main entry point class, `WebAuthnManager`.
It delegates attestation statements verification to an implementation of
`AttestationStatementVerifier` and attestation statements trustworthiness verification to an implementation of
`CertPathTrustworthinessVerifier`.

Since most sites don't require strict attestation statement verification (https://www.w3.org/TR/webauthn-1/#sctn-no-attestation-security-attestation[WebAuthn Spec related topic] ), WebAuthn4J provides `WebAuthnManager.createNonStrictWebAuthnManager` factory method that returns an `WebAuthnManager` instance configured `AttestationStatementVerifier` and
`CertPathTrustworthinessVerifier` not to verify attestation statements.

If you are engaging an enterprise use case and strict authenticator verification is a requirement, Use the constructor of the `WebAuthnManager` class and inject verifiers.

=== Attestation statement verification

Attestation statement verification is provided by the implementation of `AttestationStatementVerifier` interface.
For each attestation statement format, corresponding verifier classes are provided.
Please specify its list at the first argument of the constructor of `WebAuthnManager` class.
For example, if you would like to limit the supported format to `packed` only, add only
`PackedAttestationStatementVerifier` to the `List`, and if you would like to support `packed` and `tpm` format, make the `List` with `PackedAttestationStatementVerifier` and `TPMAttestationStatementVerifier`.

Do NOT combine no-op verifiers like `NoneAttestationStatementVerifier` or `NullPackedAttestationStatementVerifier` with other `AttestationStatementVerifier` s.
Mixing non-verifying verifiers, with verifying verifiers will create a vulnerability that can be exploited to bypass attestation verification.

==== Attestation statement trustworthiness verification

Attestation statement trustworthiness verification has two patterns: certificate path verification, and self attestation.
Certificate path verification is delegated via `CertPathTrustworthinessVerifier` interface.
WebAuthn4J provides `DefaultCertPathTrustworthinessVerifier` as `CertPathTrustworthinessVerifier` implementation.
`DefaultCertPathTrustworthinessVerifier` verifies trustworthiness by checking the attestation certificate chains to the root certificate provided as `TrustAnchor` via `TrustAnchorRepository` interface.

==== Trust anchor resolution

`TrustAnchorRepository` is an interface that resolves `TrustAnchor` from `AAGUID` or `attestationCertificateKeyIdentifier`.
`webauthn4j-core` module provides a `KeyStoreTrustAnchorRepository` as a `TrustAnchorRepository`.
`KeyStoreTrustAnchorRepository` fetches `TrustAnchor` from a Java Key Store. Please note that
`KeyStoreTrustAnchorRepository` does not return a different `TrustAnchor` depending on `AAGUID` or `attestationCertificateKeyIdentifier`.
All certificates registered in the Java Key Store file are treated as trust anchors.

===== Trust anchor resolution using FIDO Metadata Service

WARNING: `webauthn4j-metadata` module, which provides FIDO Metadata Statement handling, is under experimental status.

FIDO Alliance offers FIDO Metadata Service, which provides metadata of authenticators.
`webauthn4j-metadata` module provides a `MetadataBLOBBasedTrustAnchorRepository` as a `TrustAnchorRepository` implementation.
`MetadataBLOBBasedTrustAnchorRepository` can provide trust anchors based on the information published by FIDO Metadata Service when it is used in combination with `FidoMDS3MetadataBLOBAsyncProvider`.

=== Logging

WebAuthn4J uses SLF4J as its logging interface library.
Configure a logging implementation library, such as Logback, to output logs in your preferred style.


