== Configuration

WebAuthn4J has a one main entry point class, `WebAuthnManager`.
It delegates attestation statements validation to an implementation of
`AttestationStatementVerifier` and attestation statements trustworthiness validation to an implementation of
`CertPathTrustworthinessVerifier`.

Since most sites don't require strict attestation statement validation (https://www.w3.org/TR/webauthn-1/#sctn-no-attestation-security-attestation[WebAuthn Spec related topic] ), WebAuthn4J provides `WebAuthnManager.createNonStrictWebAuthnManager` factory method that returns an `WebAuthnManager` instance configured `AttestationStatementVerifier` and
`CertPathTrustworthinessVerifier` not to verify attestation statements.

If you are engaging an enterprise use case and strict authenticator verification is a requirement, Use the constructor of the `WebAuthnManager` class and inject validators.

=== Attestation statement validation

Attestation statement validation is provided by the implementation of `AttestationStatementVerifier` interface.
For each attestation statement format, corresponding validator classes are provided.
Please specify its list at the first argument of the constructor of `WebAuthnManager` class.
For example, if you would like to limit the supported format to `packed` only, add only
`PackedAttestationStatementVerifier` to the `List`, and if you would like to support `packed` and `tpm` format, make the `List` with `PackedAttestationStatementVerifier` and `TPMAttestationStatementVerifier`.

==== Attestation statement trustworthiness validation

Attestation statement trustworthiness validation has two patterns: certificate path validation, and self attestation.
Certificate path validation is delegated via `CertPathTrustworthinessVerifier` interface.
WebAuthn4J provides `DefaultCertPathTrustworthinessVerifier` as `CertPathTrustworthinessVerifier` implementation.
`DefaultCertPathTrustworthinessVerifier` verifies trustworthiness by checking the attestation certificate chains to the root certificate provided as `TrustAnchor` via `TrustAnchorRepository` interface.

==== Trust anchor resolution

`TrustAnchorRepository` is an interface that resolves `TrustAnchor` from `AAGUID` or `attestationCertificateKeyIdentifier`.
`webauthn4j-core` module provides a `KeyStoreTrustAnchorRepository` as a `TrustAnchorRepository`.
`KeyStoreTrustAnchorRepository` fetches `TrustAnchor` from a Java Key Store. Please note that
`KeyStoreTrustAnchorRepository` does not return a different `TrustAnchor` depending on `AAGUID` or `attestationCertificateKeyIdentifier`.
All certificates registered in the Java Key Store file are treated as trust anchors.

===== Trust anchor resolution using FIDO Metadata Service

WARNING: `webauthn4j-metadata` module, which provides FIDO Metadata Statement handling, is under experimental status.

FIDO Alliance offers FIDO Metadata Service, which provides metadata of authenticators.
`webauthn4j-metadata` module provides a `MetadataBLOBBasedTrustAnchorRepository` as a `TrustAnchorRepository` implementation.
`MetadataBLOBBasedTrustAnchorRepository` can provide trust anchors based on the information published by FIDO Metadata Service when it is used in combination with `FidoMDS3MetadataBLOBAsyncProvider`.

=== What WebAuthn4J doesn't offer

In order to realize framework independence, WebAuthn4J intentionally scopes functions to WebAuthn Assertion / Attestation verification.
Fetching parameters from HTTP request, issuing and saving Challenge in session, counter Value validation are not provided.
Please implement in your caller code.
If you are using Spring Security, consider using WebAuthn$J Spring Security as it provides these implementations of authentication framework specific parts.

