== Deep-Dive

=== Representation of an authenticator

WebAuthn4j provides `Authenticator` interface as a representation of an authenticator.

On registering the authenticator, you need to persist its representation by creating the instance implementing
`Authenticator` interface in your application manner because it is used afterwards on authentication verification.
It might be better to use credentialId as a search key for this persisted instance.

You can freely enhance the class implementing `Authenticator` interface in order to meet your application's requirements.
For example, you can add the field for your application's user to identify the authenticator.

=== Authenticator serialization and deserialization

While it is application's responsibility to serialize `Authenticator` instance at registration, WebAuthn4J provides an utility class to serialize or deserialize members of `Authenticator` class.
Please use them for implementing persistence in your application.

==== attestedCredentialData

`AttestedCredentialDataConverter` converts from `AttestedCredentialData` to `byte[]` and vice versa.
If you would like to persist as `String`, use `Base64UrlUtil` to convert from `byte[]` to base64url `String`.

[source,java]
----
AttestedCredentialDataConverter attestedCredentialDataConverter = new AttestedCredentialDataConverter(objectConverter);

// serialize
byte[] serialized = attestedCredentialDataConverter.convert(attestedCredentialData);
// deserialize
AttestedCredentialData deserialized = attestedCredentialDataConverter.convert(serialized);
----

==== attestationStatement

Since `AttestationStatement` is an interface, there are some implementation classes like `PackedAttestationStatement` or `AndroidKeyAttestationStatement` per format.
As `AttestationStatement` is not self-descriptive for its format, the format need to be persisted in an another field.
Because of that, an envelope class which has attestationStatement field and format field is required, and the envelope class need to be serialized for persisting `AttestationStatement`.

[source,java]
----
//serialize
AttestationStatementEnvelope envelope = new AttestationStatementEnvelope(attestationStatement);
byte[] serializedEnvelope = objectConverter.getCborConverter().writeValueAsBytes(envelope);

//deserialize
AttestationStatementEnvelope deserializedEnvelope = objectConverter.getCborConverter().readValue(serializedEnvelope, AttestationStatementEnvelope.class);
AttestationStatement deserializedAttestationStatement = deserializedEnvelope.getAttestationStatement();
----

[source,java]
----
class AttestationStatementEnvelope{

    @JsonProperty("attStmt")
    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
            property = "fmt"
    )
    private AttestationStatement attestationStatement;

    @JsonCreator
    public AttestationStatementEnvelope(@JsonProperty("attStmt") AttestationStatement attestationStatement) {
        this.attestationStatement = attestationStatement;
    }

    @JsonProperty("fmt")
    public String getFormat() {
        return attestationStatement.getFormat();
    }

    public AttestationStatement getAttestationStatement() {
        return attestationStatement;
    }
}
----

==== transports

If you would like to persist as JSON `String`, use `ObjectConverter`.

[source,java]
----
String serializedTransports = objectConverter.getJsonConverter().writeValueAsString(transports);
----

==== counter

This member is `long`.
Nothing special is required.

==== authenticatorExtensions

This member can be serialized as CBOR as it is originally CBOR data.

[source,java]
----
byte[] serializedAuthenticatorExtensions = objectConverter.getCborConverter().writeValueAsBytes(authenticatorExtensions);
----

==== clientExtensions

This member can be serialized as JSON as it is originally JSON data.

[source,java]
----
String serializedClientExtensions = objectConverter.getJsonConverter().writeValueAsString(clientExtensions);
----

=== DCAppleDevice serialization and deserialization

When you use `webauthn4j-device-check`, you need to persist `DCAppleDevice` instead of `Authenticator` interface between attestation and assertion.
In general, you can serialize and deserialize it by the method explained in <<Authenticator serialization and deserialization>>, but `ObjectConverter` must be the one with `DeviceCheckCBORModule` registered.
A `ObjectConverter` with a `DeviceCheckCBORModule` can be obtained with `DeviceCheckManager.createObjectConverter` static method.

=== Using FIDO CTAP2 Security key in your own application other than WebAuthn

For FIDO CTAP2 Security key, WebAuthn is just an application.
An original application can use a a security key too.
This section describes how to use WebAuthn4J for attestation and assertion validation in your own application using the FIDO CTAP2 security key.

==== Registration & Authentication flow of your own application using FIDO CTAP2 security key

If you use FIDO CTAP2 security key for authentication in your own application, you need to register the security key first.
Call the https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorMakeCredential[authenticatorMakeCredential] method of the security key to retrieve the "Attestation" data, which contains public key and device configuration and save it.
The obtained attestation data need to be validated to determine if the security key is acceptable for the application.
WebAuthn4J can validate the attestation with `CoreRegistrationValidator` class.
For authentication, the application need to call the  https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorGetAssertion[authenticatorGetAssertion] method of the security key to retrieve the "assertion" data, which contains signature.
By validating the retrieved assertion, the application can determine whether the security key used for authentication is the same as the one used for registration, and can determine whether the access is legitimate.
WebAuthn4J can validate the assertion with `CoreAuthenticationValidator` class.

==== How to validate application specific client data

Implementing the above flow will provide authentication feature, but if the entity that calls the FIDO CTAP2 security key (client) and the entity that validates the attestation and the assertion are separated, in some cases, an application specific client data is needed to be validated at the server at registration and authentication.
The client data itself can be sent together with the attestation and assertion, but in order to protect the client data from MITM attacks, it need to be signed and protected.
In FIDO CTAP2 specification, there is a parameter named `clientDataHash` that is common to https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorMakeCredential[authenticatorMakeCredential] method used at registration and https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorGetAssertion[authenticatorGetAssertion] method used at authentication.
Since the security key generates a signature from data that contains `clientDataHash`, an application can validate its specific client data by setting `clientDataHash` to the hash of the client data and validating the signature.

=== Project Modules

WebAuthn4J consists of the following four modules.

==== Core webauthn4j-core.jar

Provides core features for WebAuthn attestation and assertion verification.

==== Core webauthn4j-device-check.jar

Provides core features for Apple App Attest attestation and assertion verification.

==== Metadata webauthn4j-metadata.jar

Provides additional features regarding FIDO Metadata Service.
As FIDO Metadata Statement specification is still draft, it is in experimental status.
The included classes don't follow semantic versioning and the design may be changed even though it is public.

==== Test webauthn4j-test.jar

Internal library for WebAuthn4J testing.
The included classes don't follow semantic versioning and the design may be changed even though it is public.

==== Util webauthn4j-util.jar

Contains utility classes used in WebAuthn4J library.

=== Custom converter implementation

WebAuthn4J uses Jackson library for JSON and CBOR serialization and deserialization.
If you would like to custom serialization or deserialization, register custom serializer or deserializer to the underlying Jackson `ObjectMapper`.

==== Custom converter registration

Since WebAuthn4J wraps `ObjectMapper` with `ObjectConverter`, inject your customized `ObjectMapper` through `ObjectConverter`
constructor and specify the `ObjectConverter` instance to the `WebAuthnManager` instance creation parameter.

=== Custom validator implementation

WebAuthn4J can add custom validator.
For registration validation, implement `CustomRegistrationValidator`.
For authentication validation, implement `CustomAuthenticationValidator`.

==== Custom validator registration

`CustomRegistrationValidator` and `CustomAuthenticationValidator` implementation can be registered to `WebAuthnManager`
via its constructor's `customRegistrationValidators` and `customAuthenticationValidators` parameters.

=== Classes

==== Data Transfer Objects

Classes under `com.webauthn4j.data` package are designed as immutable DTO.

==== Converter, Jackson Modules for WebAuthn

Classes under `com.webauthn4j.data` package are designed as being serializable and deserializable.

Some Classes under `converter` package needs custom serializer and deserializer.
Jackson's module named
`WebAuthnJSONModule` and `WebAuthnCBORModule` consolidate these custom serializer and deserializer.
WebAuthn4J’s validators register these modules onto Jackson's `ObjectMapper` automatically.

If you want to use WebAuthn4J’s serializer and deserializer outside of WebAuthnManager, you can register these modules onto Jackson's `ObjectMapper`.

==== TrustAnchorsResolver

`TrustAnchorsResolver` interface is used by `TrustAnchorCertPathTrustworthinessValidator` to explore root certificates in the verification of the authenticity of the attestation statements.

==== TrustAnchorsProvider

`TrustAnchorsProvider` is an interface that `TrustAnchorsResolverImpl` delegates TrustAnchor load operation to.
KeyStoreFileTrustAnchorsProvider is provided as an implementation for loading TrustAnchor from Java Key Store file.
WebAuthn$J Spring Security also provides `CertFileResourcesTrustAnchorProvider` to load TrustAnchor from Spring Resource.

==== Exceptions

If some verification fails, WebAuthn4J throws an exception class inheriting `ValidationException`.

=== Logging

WebAuthn4J uses SLF4J as log interface library.
You can use any kind of this implementation like Logback as you want.

