[deep-dive]
== Deep-Dive

=== Project Modules

WebAuthn4J consists of the following four modules.

==== Core webauthn4j-core.jar

Provides core features for attestation and assertion verification.

==== Metadata webauthn4j-metadata.jar

Provides additional features regarding FIDO Metadata Service.

==== Test webauthn4j-test.jar

Internal library for WebAuthn4J testing. The included classes don't follow semantic versioning and the design
may be changed even though it is public.

==== Util webauthn4j-util.jar

Contains utility classes used in WebAuthn4J library.

=== Classes

==== Request/Response

Classes under `com.webauthn4j.request`, `com.webauthn4j.request` package are designed as immutable DTO.

==== Converter, WebAuthnModule

Classes under `com.webauthn4j.request`, `com.webauthn4j.request` package are designed as being serializable and deserializable.

Classes under `converter` package needs custom serializer and deserializer. Jackson’s module named `WebAuthnModule` consolidates these custom serializer and deserializer. WebAuthn4J’s validators register `WebAuthnModule` onto Jackson’s `ObjectMapper` automatically. 

If you want to use WebAuthn4J’s serializer and deserializer outside these WebAuthn4J’s validators, you can register `WebAuthnModule` onto Jackson’s `ObjectMapper`.

If you want to use your custom serializer and deserializer for WebAuthn4J’s validators, you can register your custom serializer and deserializer onto `ObjectMapper` and pass it onto WebAuthn4J’ validators via those constructors.

==== TrustAnchorsResolver



==== TrustAnchorsProvider


==== MetadataItemsResolver


==== Exceptions

If some verification fails, WebAuthn4J throws an exception class inheriting `ValidationException`.

=== Logging

WebAuthn4J uses SLF4J as log interface library. You can use any kind of this implementation like Logback as you want.

