== Deep-Dive

=== Using FIDO CTAP2 Security key in your own application other than WebAuthn

For FIDO CTAP2 Security key, WebAuthn is just an application. An original application can use a a security key too.
This section describes how to use WebAuthn4J for attestation and assertion validation in your own application using the FIDO CTAP2 security key.

==== Registration & Authentication flow of your own application using FIDO CTAP2 security key

If you use FIDO CTAP2 security key for authentication in your own application, you need to register the security key first.
Call the https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorMakeCredential[authenticatorMakeCredential] method of the security key
to retrieve the "Attestation" data, which contains public key and device configuration and save it.
The obtained attestation data need to be validated to determine if the security key is acceptable for the application. WebAuthn4J can validate the attestation with `CoreRegistrationValidator` class.
For authentication, the application need to call the  https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorGetAssertion[authenticatorGetAssertion] method of the security key to retrieve the "assertion" data, which contains signature.
By validating the retrieved assertion, the application can determine whether the security key used for authentication is the same as the one used for registration, and can determine whether the access is legitimate. WebAuthn4J can validate the assertion with `CoreAuthenticationValidator` class.

==== How to validate application specific client data

Implementing the above flow will provide authentication feature, but if the entity that calls the FIDO CTAP2 security key (client) and the entity that validates the attestation and the assertion are separated, in some cases, an application specific client data is needed to be validated at the server at registration and authentication. The client data itself can be sent together with the attestation and assertion, but in order to protect the client data from MITM attacks, it need to be signed and protected.
In FIDO CTAP2 specification, there is a parameter named `clientDataHash` that is common to https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorMakeCredential[authenticatorMakeCredential] method used at registration and https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorGetAssertion[authenticatorGetAssertion] method used at authentication.
Since the security key generates a signature from data that contains `clientDataHash`, an application can validate its specific client data by setting `clientDataHash` to the hash of the client data and validating the signature.

=== Project Modules

WebAuthn4J consists of the following four modules.

==== Core webauthn4j-core.jar

Provides core features for attestation and assertion verification.

==== Metadata webauthn4j-metadata.jar

Provides additional features regarding FIDO Metadata Service.
As FIDO Metadata Statement specification is still draft, it is in experimental status.
The included classes don't follow semantic versioning and the design may be changed even though it is public.

==== Test webauthn4j-test.jar

Internal library for WebAuthn4J testing. The included classes don't follow semantic versioning and the design
may be changed even though it is public.

==== Util webauthn4j-util.jar

Contains utility classes used in WebAuthn4J library.

=== Custom converter implementation

WebAuthn4J uses Jackson library for JSON and CBOR serialization and deserialization.
If you would like to custom serialization or deserialization, register custom serializer or deserializer to the
underlying Jackson `ObjectMapper`.

==== Custom converter registration

Since WebAuthn4J wraps `ObjectMapper` with `ObjectConverter`, inject your customized `ObjectMapper` through `ObjectConverter`
constructor and specify the `ObjectConverter` instance to the `WebAuthnManager` instance creation parameter.

=== Custom validator implementation

WebAuthn4J can add custom validator.
For registration validation, implement `CustomRegistrationValidator`.
For authentication validation, implement `CustomAuthenticationValidator`.

==== Custom validator registration

`CustomRegistrationValidator` and `CustomAuthenticationValidator` implementation can be registered to `WebAuthnManager`
via its constructor's `customRegistrationValidators` and `customAuthenticationValidators` parameters.

=== Classes

==== Data Transfer Objects

Classes under `com.webauthn4j.data` package are designed as immutable DTO.

==== Converter, Jackson Modules for WebAuthn

Classes under `com.webauthn4j.data` package are designed as being serializable and deserializable.

Some Classes under `converter` package needs custom serializer and deserializer. Jackson's module named
`WebAuthnJSONModule` and `WebAuthnCBORModule` consolidate these custom serializer and deserializer.
WebAuthn4J’s validators register these modules onto Jackson's `ObjectMapper` automatically.

If you want to use WebAuthn4J’s serializer and deserializer outside of WebAuthnManager,
you can register these modules onto Jackson's `ObjectMapper`.

==== TrustAnchorsResolver

`TrustAnchorsResolver` interface is used by `TrustAnchorCertPathTrustworthinessValidator` to explore root certificates
in the verification of the authenticity of the attestation statements.

==== TrustAnchorsProvider

`TrustAnchorsProvider` is an interface that `TrustAnchorsResolverImpl` delegates TrustAnchor load operation to.
KeyStoreFileTrustAnchorsProvider is provided as an implementation for loading TrustAnchor from Java Key Store file.
Spring Security WebAuthn also provides `CertFileResourcesTrustAnchorProvider` to load TrustAnchor from Spring Resource.

==== Exceptions

If some verification fails, WebAuthn4J throws an exception class inheriting `ValidationException`.

=== Logging

WebAuthn4J uses SLF4J as log interface library. You can use any kind of this implementation like Logback as you want.

