== Introduction

=== What is Web Authentication?

Web Authentication is a new, secure web application authentication specification standardized under W3C.
By combining local authentication, public-key authentication, per-origin key management, it provides strong authentication to web sites against authentication process attacks like phishing.
It is implemented in major browsers, offering an excellent choice for users who prioritize security and convenience.

=== What is Passkeys?

Passkeys is a user-friendly branding name for WebAuthn Level 3, designed to improve the usability of the WebAuthn specification.

=== WebAuthn4J

WebAuthn4J is a Java library for WebAuthn and Apple App Attest server side verification.
It can be used not only for server-side verification of WebAuthn/Passkeys, but also for custom applications that use Apple App Attest or FIDO CTAP2 security keys.
It is a portable library that supports all attestation statement formats defined in the Web Authentication specification while keeping external dependencies to a minimum.

=== WebAuthn4J Spring Security

As a related project of WebAuthn4J, we are developing a wrapper library named https://github.com/webauthn4j/webauthn4j-spring-security[WebAuthn4J Spring Security]
to support WebAuthn with Spring Security.
To introduce WebAuthn in an application built with Spring Security, it is better to use WebAuthn4J Spring Security rather than directly using WebAuthn4J.

=== Feature

==== Supported Attestation Statement Formats

All attestation statement formats are supported:

- Packed attestation
- FIDO U2F attestation
- Android Key attestation
- Android SafetyNet attestation
- TPM attestation
- Apple Anonymous attestation
- Apple App Attest attestation
- None attestation

==== Conformance

All mandatory test cases and optional Android Key attestation test cases of https://fidoalliance.org/certification/functional-certification/conformance/[FIDO2 Test Tools provided by FIDO Alliance]
are passed.

NOTE: Since FIDO2 Test Tools runs the test via the REST API of FIDO2 Transport Binding Profile, it is executed through the REST API implementation provided by WebAuthn4j Spring Security.

==== Portability

WebAuthn4J only depends on SLF4J and Jackson, offering very high portability. There should be almost no barriers to introducing webauthn4j into your Java application.

=== Requirements

==== Language & Framework

- Java 11 or later (Java 17 or later if using EdDSA)

==== Environment

- SecureContext (https or the localhost)

=== Getting from Maven Central

If you are using Maven, just add the webauthn4j as a dependency:

[source,xml]
----
<properties>
  ...
  <!-- Use the latest version whenever possible. -->
  <webauthn4j.version>0.28.2.RELEASE</webauthn4j.version>
  ...
</properties>

<dependencies>
  ...
  <dependency>
    <groupId>com.webauthn4j</groupId>
    <artifactId>webauthn4j-core</artifactId>
    <version>${webauthn4j.version}</version>
  </dependency>
  ...
</dependencies>
----

=== Source code

Source code for this project is hosted on https://github.com/webauthn4j/webauthn4j[Github].

----
git clone git@github.com:webauthn4j/webauthn4j.git
----

=== License

WebAuthn4J is an open source software licensed under https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 License].

=== Contributing

Thank you for your interest in WebAuthn4J. Your participation is much appreciated!
Please feel free to open issues and send pull-requests.

