[introduction]
== Introduction

=== Web Authentication

Web Authentication is a new, secure web application authentication specification standardizing under W3C.
By combining local authentication, public-key authentication, per-origin key management,
it provides strong authentication to web sites against authentication process attacks like phishing.
Implementation is in progress in major browsers, the specification offers excellent choices for users who place importance on security and convenience.
Initially, the specification was developed as FIDO 2.0 by the FIDO Alliance, but it has been transferred to W3C.

=== WebAuthn4J

WebAuthn4J is a portable Java library for WebAuthn assertion verification

==== Supported Attestation Statement Formats

List of supported attestation statement formats is below:

- None Attestation Statement Format
- FIDO-U2F Attestation Statement Format

Other attestation statement formats are also planed to support.

=== Requirements

==== Language & Framework

- Java8 or later

==== Environment

- SecureContext（connected by https or the localhost）

=== Source code

Source code for this project is hosted on https://github.com/webauthn4j/webauthn4j[Github].
----
git clone git@github.com:webauthn4j/webauthn4j.git
----

=== License

WebAuthn4J is an open source software licensed under http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

