== Quick Start

In this quick start guide, we’ll introduce an overview of the WebAuthn authentication process, and then details the scope, limitations, and how to implement WebAuthn authentication using the WebAuthn4J library.

=== Overview of WebAuthn Authentication process

==== Authentication Flow

In short, WebAuthn authentication is a public key-based authentication method designed for web applications.

First, a key pair is generated, with the public key stored on the server and the private key kept on the authenticator. At the time of authentication, the authenticator uses the private key to generate a signature, which is sent to the server to be verified with the public key, confirming the user's identity.

The signed data comprises from the client data and the authenticator data.
The client data contains not only the domain (origin) of the displayed site, but also the server-related information like a challenge generated beforehand by the server.
The server not only verifies the signature but also confirms the challenge, helping to prevent replay attacks.
Various other data and are also included in the signed client data and authenticator data, and the server verifies these as well.
The data flow during authentication is illustrated in the diagram below.

[plantuml,authentication sequence,svg]
....
@startuml
title WebAuthn Authentication Overview
autonumber
actor "User"
participant "Authenticator"
participant "Client"
participant "Server"
database Session

"Server" -> "Server": generate challenge
"Server" -> "Session": challenge
"Server" -> "Client": challenge

"Client" -> "Client": generate client data (challenge, origin, etc.)
"Client" -> "Authenticator": credential request (client data hash, etc.)
"Authenticator" -> "User": consent request
"User" -> "Authenticator": authorization gesture
"Authenticator" -> "Authenticator": generate authenticator data (user verification status, etc)
"Authenticator" -> "Authenticator": sign over authenticator data and client data hash
"Authenticator" -> "Client": credential response (authenticator data, signature, etc.)
"Client" -> "Server": assertion \n (authenticator data, client data, signature, etc.)
"Session" -> "Server": load challenge
"Server" -> "Server": verify

@enduml
....

==== Registration Flow

In the WebAuthn new credential registration process, the client asks the authenticator to generate a new key pair, and the public key and other data returned by the authenticator are registered on the server as credentials.
Interestingly, the new credential registration follows a flow similar to authentication: the authenticator first signs the client data, including the challenge from the server and the authenticator data, then returns it.
The server receives this via the client, verifies the signature, and, if successful, registers it as a credential record.
For registration, however, the signed authenticator data also includes the newly generated public key, which is saved on the server and later used for signature verification in the authentication process.

The data flow during registration is illustrated in the diagram below.

[plantuml,registration sequence,svg]
....
@startuml
title WebAuthn Registration Overview
autonumber
actor "User"
participant "Authenticator"
participant "Client"
participant "Server"
database Session

"Server" -> "Server": generate challenge
"Server" -> "Session": challenge
"Server" -> "Client": challenge

"Client" -> "Client": generate client data (challenge, origin, etc.)
"Client" -> "Authenticator": credential request (client data hash, etc.)
"Authenticator" -> "User": consent request
"User" -> "Authenticator": authorization gesture
"Authenticator" -> "Authenticator": generate authenticator data\n(credential public key, user verification status, etc.)
"Authenticator" -> "Authenticator": sign over authenticator data and client data hash
"Authenticator" -> "Authenticator": generate attestation statement\n(authenticator attestation, signature, etc.)
"Authenticator" -> "Client": credential response\n(authenticator data, attestation statement, etc.)
"Client" -> "Server": attestation \n (authenticator data, client data, attestation statement, etc.)
"Session" -> "Server": load challenge
"Server" -> "Server": verify

@enduml
....

As explained in the previous section, during authentication, the signature is created with the credential’s private key and verified with the credential’s public key. But then, what private key is used to sign the authenticator data and client data during the registration of the credential's public key?
And how does the server obtain the public key necessary for this signature verification?
Typically, this private key is a unique key specific to each model of the authenticator and is embedded in the authenticator in advance. As for the public key used in verification, it can either be preconfigured on the server for trusted authenticator or obtained from a registry, such as the FIDO Metadata Service, which provides public keys for each authenticator model.

In this way, WebAuthn has a mechanism called "Attestation" that verifies that the authenticator being registered is of a specific model by signing the credential public key registration message with a model-specific private key.
This data structure containing attestation information is called the "Attestation Statement". However, because the attestation statement reveals the model of the user’s authenticator, it could potentially be used for user tracking.

Therefore, in the default configuration, even if the authenticator returns an attestation statement, the client discards it and does not send it to the server.
The attestation statement is only disclosed if explicitly specified as an option and with the end user’s consent.

=== Scope of WebAuthn4J

To achieve portability by not relying on any particular web application framework, WebAuthn4J intentionally narrows its functionality scope to server-side verification of  WebAuthn registration and authentication.

[plantuml,webauthn4j scope,svg]
....
@startuml
title WebAuthn4J Scope
autonumber
actor "User"
participant "Authenticator"
participant "Client"
participant "Server"
database Session

"Server" -> "Server": generate challenge
"Server" -> "Session": challenge
"Server" -> "Client": challenge

"Client" -> "Client": generate client data (challenge, origin, etc.)
"Client" -> "Authenticator": credential request (client data hash, etc.)
"Authenticator" -> "User": consent request
"User" -> "Authenticator": authorization gesture
"Authenticator" -> "Authenticator": generate authenticator data (user verification status, etc)
"Authenticator" -> "Authenticator": sign over authenticator data and client data hash
"Authenticator" -> "Client": credential response (authenticator data, signature, etc.)
"Client" -> "Server": assertion \n (authenticator data, client data, signature, etc.)
"Session" -> "Server": load challenge
group WebAuthn4J scope
"Server" -> "Server": verify
end

@enduml
....

For this reason, WebAuthn4J does not provide functions for retrieving parameters from HTTP requests, storing challenges in sessions, returning them to the frontend, saving generated public keys as credential records, or loading these records during authentication.
These functions must be implemented according to the framework you are using.

If a WebAuthn4J wrapper library that manages these functions is available for your framework, it’s recommended to use it. For example:

- Quarkus Security WebAuthn
- Spring Security Passkeys
- Vert.x Auth WebAuthn4J

If no wrapper library is available, you will need to implement these functions yourself, which will be explained in the next section.

=== Implementing the Registration Process Using WebAuthn4J

==== Generating a WebAuthn credential key pair

When calling the `navigator.credentials.create` method, various options can be specified. One of these options is `challenge`. As mentioned earlier, the challenge is a parameter used to prevent replay attacks; it should be generated by the server, passed as a parameter, and also saved in a session or similar storage.
According to the registration flow diagram, the backend server first generates the challenge, saves it in a session, and then sends it to the client.
The WebAuthn specification does not define a specific method for passing the challenge from the backend server to the frontend. You could embed it in an HTML page or set up a REST endpoint to return the challenge. Another good idea is to create an endpoint that returns the entire `PublicKeyCredentialCreationOptions`, a parameter for `navigator.credentials.create`. The WebAuthn JavaScript API provides a method called `PublicKeyCredential.parseCreationOptionsFromJSON`, which can parse a serialized JSON `PublicKeyCredentialCreationOptions`.
However, `PublicKeyCredential.parseCreationOptionsFromJSON` is not available on Safari versions earlier than 18.4.
For alternative solutions, refer to <<./deep-dive.adoc#_alternative_to_unsupported_json_serialization_apis_in_safari, Alternative to Unsupported JSON Serialization APIs in Safari>>.

WebAuthn4J offers a Java class representing `PublicKeyCredentialCreationOptions`, which can be useful for assembling JSON on the backend server.

.Fetching the entire `PublicKeyCredentialCreationOptions` from the REST endpoint and calling `navigator.credentials.create`
[source,javascript,caption="Example {counter:number}: "]
----
const response = await fetch("/passkeys/attestationOptions") //fetch PublicKeyCredentialCreationOptions as JSON string
const publicKeyCredentialCreationOptionsJSON = await response.json() // convert to JSONObject
const credentialCreationOptions = PublicKeyCredential.parseCreationOptionsFromJSON(publicKeyCredentialCreationOptionsJSON); // convert to PublicKeyCredentialCreationOptions
const publicKeyCredential = await navigator.credentials.create({ publicKey: credentialCreationOptions}); // create PublicKeyCredential
----

In any case, generate the challenge on the backend server, store it in the session, and pass it to the frontend by some means.
Then, in the frontend JavaScript, call the `navigator.credentials.create` method with it to generate the WebAuthn credential. For more information on the other options available for the `navigator.credentials.create` method, please refer https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create[MDN: CredentialsContainer: create() method].

==== Registering the WebAuthn public key credential on the server

The generated WebAuthn credential must be sent to the backend server in some way.
The WebAuthn specification does not define the format in which it should be sent to the server.
However, the JavaScript type `PublicKeyCredential`, representing a WebAuthn credential, has a `toJSON` method.
Using this method along with `JSON.stringify` to serialize the data is considered a best practice for transmission.
However, this `toJSON` method is also not available in Safari.
For alternative solutions, refer to <<./deep-dive.adoc#Alternative-to-Unsupported-JSON-Serialization-APIs-in-Safari,Alternative to Unsupported JSON Serialization APIs in Safari>>.

.Sending `PublicKeyCredential`
[source,javascript,caption="Example {counter:number}: "]
----
const registrationResponseJSON = publicKeyCredential.toJSON(); // convert to JSONObject
await fetch("/register", {
    method : 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: new URLSearchParams({
        'username': document.getElementById('username').value,
        'registrationResponseJSON': JSON.stringify(registrationResponseJSON) //convert to string
    })
});
----

The backend server needs to verify the received WebAuthn credential and then persist the WebAuthn credential record, which includes the public key.
With WebAuthn4J, you can directly verify the JSON representation of PublicKeyCredential using the `WebAuthnManager#verifyRegistrationResponseJSON` method. The `WebAuthnManager#parseRegistrationResponseJSON` method only performs deserialization of `PublicKeyCredential` without verification.
If you want to access the parsed data when an error occurs during verification, parse it with `WebAuthnManager#parseRegistrationResponseJSON` to obtain an instance of `RegistrationData`, then pass it to the `WebAuthnManager#verify` method for verification.


.Server-side verification of `PublicKeyCredential`
[source,java,caption="Example {counter:number}: "]
----
String registrationResponseJSON = "<registrationResponseJSON>"; /* set registrationResponseJSON received from frontend */
RegistrationData registrationData;
try {
    registrationData = webAuthnManager.parseRegistrationResponseJSON(registrationResponseJSON);
}
catch (DataConversionException e) {
    // If you would like to handle WebAuthn data structure parse error, please catch DataConversionException
    throw e;
}

// Server properties
Origin origin = null /* set origin */;
String rpId = null /* set rpId */;
Challenge challenge = null /* set challenge */;
ServerProperty serverProperty = ServerProperty.builder()
        .origin(origin)
        .rpId(rpId)
        .challenge(challenge)
        .build();

// expectations
List<PublicKeyCredentialParameters> pubKeyCredParams = null;
boolean userVerificationRequired = false;
boolean userPresenceRequired = true;

RegistrationParameters registrationParameters = new RegistrationParameters(serverProperty, pubKeyCredParams, userVerificationRequired, userPresenceRequired);

try {
    webAuthnManager.verify(registrationData, registrationParameters);
} catch (VerificationException e) {
    // If you would like to handle WebAuthn data verification error, please catch VerificationException
    throw e;
}

// please persist CredentialRecord object, which will be used in the authentication process.
CredentialRecord credentialRecord =
        new CredentialRecordImpl( // You may create your own CredentialRecord implementation to save friendly authenticator name
                registrationData.getAttestationObject(),
                registrationData.getCollectedClientData(),
                registrationData.getClientExtensions(),
                registrationData.getTransports()
        );
save(credentialRecord); // please persist credentialRecord in your manner
----

`RegistrationParameters` is another argument of the `WebAuthnManager#verifyRegistrationResponseJSON` method, containing parameters that encapsulate the server state and verification conditions.

- `serverProperty`: A parameter that conveys the server state. See <<ServerProperty>> for details.
- `pubKeyCredParams`: Specify the same value as the `pubKeyCredParams` provided in `PublicKeyCredentialCreationOptions`.
- `userVerificationRequired`: A parameter indicating whether user verification, such as biometrics or PIN confirmation on the authenticator, is required.
- `userPresenceRequired`: A parameter specifying whether the user’s presence verification on the authenticator is mandatory.
This verifies the `UP` flag, which indicates that the user performed some gesture input. This gesture could be something like a touch on a capacitive button, not limited to biometric authentication. In WebAuthn, the `UP` flag is generally required, so it should be set to `true`, except in scenarios that auto-generating credentials during a password-to-passkey upgrade, where `false` is required.

==== ServerProperty

The server state is encapsulated in `serverProperty`. When creating the `ServerProperty` (via the builder), specify the following values:

* For `origin`, specify the origin you expect the client browser (user agent) to have recognized at the time of the WebAuthn registration and authentication ceremony. The browser writes the recognized origin to clientData and includes this content in the signature. On the server side, by verifying that the origin recorded in clientData matches the expected value, you can prevent ceremonies that are fraudulently launched from unexpected pages or other origins (phishing and framing attacks).
* For `rpId`, specify the rpId of the site providing WebAuthn authentication. rpId is a parameter that specifies the scope of the credentials. For details, see the rpId section of the WebAuthn specification.
* For `challenge`, specify the issued challenge. `challenge` is a parameter to prevent replay attacks. You can protect users from replay attacks by generating a random byte sequence as a `challenge` on the server side, specifying it as a parameter when executing the WebAuthn JS API on the front-end, including it in the signature, and verifying that the values ​​match on the server side. It is the responsibility of the WebAuthn4J library caller to persist the issued challenge until verification. It is a good idea to store it in the session or somewhere similar.
* (Optional) You can specify the top origins to allow by using `topOrigin(...)`/`topOrigins(...)`/`topOriginPredicate(...)`.
** WebAuthn does not allow cross-origin access in principle, due to the same-origin constraint and clickjacking countermeasures.
** However, in use cases such as embedding an authentication widget on a site with a different origin, you may want to allow access only from specific parent pages. In that case, please explicitly specify the parent pages (origin of the top-level document) you want to allow using `topOrigin(...)`/`topOrigins(...)`/`topOriginPredicate(...)`. If you absolutely need to allow any parent page, you can use `anyTopOrigin()`, but this should be used with caution as it increases the attack surface.
** Example (Allow only specific parent pages):
+
[source,java]
----
ServerProperty serverProperty = ServerProperty.builder()
.origin(new Origin("https://rp.example.com"))
.rpId("rp.example.com")
.challenge(challenge)
.topOrigin(new Origin("https://parent.example.com"))
.build();
----
** Example (Allow/Disable any parent page):
+
[source,java]
----
ServerProperty serverProperty = ServerProperty.builder()
.origin(new Origin("https://rp.example.com"))
.rpId("rp.example.com")
.challenge(challenge)
.anyTopOrigin()
.build();
----

If verification succeeds, create a `CredentialRecord` instance from the returned values and persist it in a database or similar storage for authentication.
For more information on persistence methods, see <<_credentialrecord_serialization_and_deserialization, Credential Record serialization and deserialization>>.
If verification fails, a subclass of `VerificationException` will be thrown.

=== Implementing the Authentication Process Using WebAuthn4J

==== Generating a WebAuthn Assertion

The primary API used during WebAuthn authentication is the browser’s `navigator.credentials.get` method. As illustrated in the authentication flow diagram, first the backend server needs to generate a challenge, save it in a session, and pass it to the client.
This is necessary because the `navigator.credentials.get` method requires a `challenge` parameter.
The WebAuthn specification does not define a specific method for transferring the challenge from the backend server to the frontend (client) for authentication.
Just as with the registration process, feel free to use any preferred method to pass the challenge to the frontend. The JavaScript API for parsing `PublicKeyCredentialRequestOptions`, a parameter of `navigator.credentials.get`, is `PublicKeyCredential.parseCreationGetOptionsFromJSON`.
For alternative solutions to the issue that `PublicKeyCredential.parseCreationGetOptionsFromJSON` is not available in Safari, refer to <<./deep-dive.adoc#_alternative_to_unsupported_json_serialization_apis_in_safari,Alternative to Unsupported JSON Serialization APIs in Safari>>.
For additional options that can be specified for the `navigator.credentials.get` method, please refer https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get[MDN: CredentialsContainer: get() method].


.Retrieving the entire `PublicKeyCredentialRequestOptions` from the REST endpoint and calling
`navigator.credentials.get`
[source,javascript,caption="Example {counter:number}: "]
----
const response = await fetch("/passkeys/assertionOptions");
const publicKeyCredentialRequestOptionsJSON = await response.json();
const credentialGetOptions = PublicKeyCredential.parseRequestOptionsFromJSON(publicKeyCredentialRequestOptionsJSON);
const publicKeyCredential = await navigator.credentials.get({ publicKey: credentialGetOptions});
----


==== WebAuthn Assertion Verification and Post-Processing

The assertion generated by the `navigator.credentials.get` method needs to be sent to the backend server for verification.
As with the registration, it can be serialized using the `toJSON` method.

.Sending `PublicKeyCredential`
[source,javascript,caption="Example {counter:number}: "]
----
const authenticationResponseJSON = publicKeyCredential.toJSON();
console.debug("authenticationResponseJSON: %s", authenticationResponseJSON);
await fetch("/passkeys/authenticate", {
    method : 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify(authenticationResponseJSON)
});
----

With WebAuthn4J, you can verify the JSON representation of `PublicKeyCredential` using the `WebAuthnManager#verifyAuthenticationResponseJSON` method.
If you wish to perform parsing and verification as two separate steps, use the `WebAuthnManager#parseAuthenticationResponseJSON` and `WebAuthnManager#verify` methods.

.Server-side verification of `PublicKeyCredential`
[source,java,caption="Example {counter:number}: "]
----
String authenticationResponseJSON = "<authenticationResponseJSON>"; /* set authenticationResponseJSON received from frontend */

AuthenticationData authenticationData;
try {
    authenticationData = webAuthnManager.parseAuthenticationResponseJSON(authenticationResponseJSON);
} catch (DataConversionException e) {
    // If you would like to handle WebAuthn data structure parse error, please catch DataConversionException
    throw e;
}

// Server properties
Origin origin = null /* set origin */;
String rpId = null /* set rpId */;
Challenge challenge = null /* set challenge */;
ServerProperty serverProperty = ServerProperty.builder()
        .origin(origin)
        .rpId(rpId)
        .challenge(challenge)
        .build();

// expectations
List<byte[]> allowCredentials = null;
boolean userVerificationRequired = true;
boolean userPresenceRequired = true;

CredentialRecord credentialRecord = load(authenticationData.getCredentialId()); // please load authenticator object persisted in the registration process in your manner
AuthenticationParameters authenticationParameters =
        new AuthenticationParameters(
                serverProperty,
                credentialRecord,
                allowCredentials,
                userVerificationRequired,
                userPresenceRequired
        );

try {
    webAuthnManager.verify(authenticationData, authenticationParameters);
} catch (VerificationException e) {
    // If you would like to handle WebAuthn data validation error, please catch ValidationException
    throw e;
}
// please update the counter of the authenticator record
updateCounter(
        authenticationData.getCredentialId(),
        authenticationData.getAuthenticatorData().getSignCount()
);
----
Note: Origin verification checks that the Origin recognized by the browser at the time of the ceremony matches your expected Origin. Cross‑origin iframe execution is disallowed by default. For legitimate embedding use cases, explicitly configure server‑side acceptance of specific parent origins via the ServerProperty builder (`topOrigin(...)`/`topOrigins(...)`/`topOriginPredicate(...)`), or use `anyTopOrigin()` only if strictly necessary. The client’s `crossOrigin` value is a supplemental signal; the server’s top‑origin configuration determines allow/deny.

The `AuthenticationParameters`, which is another argument of the `WebAuthnManager#verifyAuthenticationResponseJSON` method, is a parameter that encapsulates the server’s state and verification conditions.

- `serverProperty`: A parameter that conveys the server’s state. For more information, refer to <<ServerProperty>>.
- `userVerificationRequired`: A parameter specifies whether user verification, like biometric authentication or PIN confirmation on the authenticator is required.
For multi-step authentication involving a password and device possession, this can be set to `false`, as the password confirms knowledge factor.
For password-less authentication, this should be set to `true`.
- `authenticator`: Specify the `CredentialRecord` that was persisted during registration.

If verification succeeds, the authentication is considered successful, and the `counter`,
`uvInitialized`, and `backedUp` values linked to the persisted `CredentialRecord` should be updated.
The counter is used to detect cloning of the authenticator. For details on counters, see https://www.w3.org/TR/webauthn-1/#sign-counter[the counter section of the WebAuthn specification].
Then, complete any necessary steps for successful user authentication, such as creating an authenticated session.

If verification fails, a subclass of `VerificationException` will be thrown.



=== Apple App Attest verification

Next, how to verify Apple App Attest is explained.
Since Apple App Attest has a data structure similar to WebAuthn, the validator design follows that of WebAuthn.
Risk metric evaluation is not supported for now.

==== Getting from Maven Central

Apple App Attest validators are contained in the dedicated `webauthn4j-appattest` module.
If you are using maven, add the `webauthn4j-appattest` as a dependency in this way:

[source,xml]
----
<properties>
  ...
  <!-- Use the latest version whenever possible. -->
  <webauthn4j.version>0.31.0.RELEASE</webauthn4j.version>
  ...
</properties>

<dependencies>
  ...
  <dependency>
    <groupId>com.webauthn4j</groupId>
    <artifactId>webauthn4j-appattest</artifactId>
    <version>${webauthn4j.version}</version>
  </dependency>
  ...
</dependencies>
----

==== Apple App Attest attestation verification

To verify an attestation on authenticator registration, call `DeviceCheckManager#verify` with a
`DCAttestationRequest` instance as an argument.
If you would like to access the parsed data when an validation error occurred, please use `DeviceCheckManager#parse` to parse the attestation request and pass the returned `DCAttestationData` instance to `DeviceCheckManager#verify`
method.

The members of `DCAttestationRequest` are the values obtained by the Apple App Attest API in the iOS device Transmit from the iOS device to the server side in some way.

`DCAttestationParameters` is an another argument for `DeviceCheckManager#parse` method, and contains server property and validation conditions.

`DCServerProperty` has following members.

- For `teamIdentifier`, please set the teamIdentifier used for your iOS App development.
For more details, please refer to
https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server[Validating Apps that connect to your server].

- For `cfBundleIdentifier`, please set the cfBundleIdentifier used for your iOS App development.
For more details, please refer to
https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server[Validating Apps that connect to your server].

- For `challenge`, please specify the Challenge issued on App Attest API call. `challenge` is a parameter to prevent replay attacks.
By issuing the random byte sequence `challenge` on server side, signing it with App Attest API, and verifying the signature on server side, users are protected from the replay attack.
It is the application's responsibility for retaining the issued Challenge.

If validation fails, an exception inheriting `VerificationException` is thrown.
If validation succeeds, please create an `DCAppleDevice` instance from the returned value and persist it to the database or something in your application manner.
The instance is required at the time of authentication.

===== Production environment? Development environment?

Apple App Attest can return a development attestation for development.
By default, webAuthn4j-appattest is set to accept a production attestation.
If you want to accept a development attestation, you need to `DCAttestationDataVerifier#setProduction` `false`.

[source,java]
----
// Client properties
byte[] keyId = null; /* set keyId */
byte[] attestationObject = null; /* set attestationObject */
byte[] challenge = null; /* set challenge */
byte[] clientDataHash = MessageDigestUtil.createSHA256().digest(challenge);

// Server properties
String teamIdentifier = null /* set teamIdentifier */;
String cfBundleIdentifier = null /* set cfBundleIdentifier */;
DCServerProperty dcServerProperty = new DCServerProperty(teamIdentifier, cfBundleIdentifier, new DefaultChallenge(challenge));

DCAttestationRequest dcAttestationRequest = new DCAttestationRequest(keyId, attestationObject, clientDataHash);
DCAttestationParameters dcAttestationParameters = new DCAttestationParameters(dcServerProperty);
DCAttestationData dcAttestationData;
try {
    dcAttestationData = deviceCheckManager.parse(dcAttestationRequest);
} catch (DataConversionException e) {
    // If you would like to handle Apple App Attest data structure parse error, please catch DataConversionException
    throw e;
}
try {
    deviceCheckManager.verify(dcAttestationData, dcAttestationParameters);
} catch (VerificationException e) {
    // If you would like to handle Apple App Attest data validation error, please catch VerificationException
    throw e;
}

// please persist Authenticator object, which will be used in the authentication process.
DCAppleDevice dcAppleDevice =
        new DCAppleDeviceImpl( // You may create your own Authenticator implementation to save friendly authenticator name
                dcAttestationData.getAttestationObject().getAuthenticatorData().getAttestedCredentialData(),
                dcAttestationData.getAttestationObject().getAttestationStatement(),
                dcAttestationData.getAttestationObject().getAuthenticatorData().getSignCount(),
                dcAttestationData.getAttestationObject().getAuthenticatorData().getExtensions()
        );
save(dcAppleDevice); // please persist authenticator in your manner
----

==== Apple App Attest assertion verification

To parse and verify an assertion on authentication, call `DeviceCheckManager#verify` with a `DCAssertionRequest`
instance as an argument.
If you would like to access the parsed data when an validation error occurred, please use
`DeviceCheckManager#parse` to parse the authentication request and pass the returned `DCAssertionData` instance to `DeviceCheckManager#verify` method.

The members of `DCAssertionRequest` are the values obtained by the App Attest API in the iOS device.
Transmit from the iOS device to the server side in some way.

DCAssertionParameters is an another argument for DeviceCheckManager#parse method, and contains server property, persisted authenticator and validation conditions.

[source,java]
----
// Client properties
byte[] keyId = null /* set keyId */;
byte[] assertion = null /* set assertion */;
byte[] clientDataHash = null /* set clientDataHash */;

// Server properties
String teamIdentifier = null /* set teamIdentifier */;
String cfBundleIdentifier = null /* set cfBundleIdentifier */;
byte[] challenge = null;
DCServerProperty dcServerProperty = new DCServerProperty(teamIdentifier, cfBundleIdentifier, new DefaultChallenge(challenge));

DCAppleDevice dcAppleDevice = load(keyId); // please load authenticator object persisted in the attestation process in your manner

DCAssertionRequest dcAssertionRequest =
        new DCAssertionRequest(
                keyId,
                assertion,
                clientDataHash
        );
DCAssertionParameters dcAssertionParameters =
        new DCAssertionParameters(
                dcServerProperty,
                dcAppleDevice
        );

DCAssertionData dcAssertionData;
try {
    dcAssertionData = deviceCheckManager.parse(dcAssertionRequest);
} catch (DataConversionException e) {
    // If you would like to handle Apple App Attest data structure parse error, please catch DataConversionException
    throw e;
}
try {
    deviceCheckManager.verify(dcAssertionData, dcAssertionParameters);
} catch (ValidationException e) {
    // If you would like to handle Apple App Attest data validation error, please catch ValidationException
    throw e;
}
// please update the counter of the authenticator record
updateCounter(
        dcAssertionData.getCredentialId(),
        dcAssertionData.getAuthenticatorData().getSignCount()
);
----


