== 設定

WebAuthn4Jを利用する上で中心となるクラスは `WebAuthnManager` クラスです。
`WebAuthnManager` は登録リクエスト検証時の構成証明ステートメントの署名と信頼性の検証は、 それぞれ `AttestationStatementVerifier` と `CertPathTrustworthinessVerifier` インタフェースの実装に委譲します。

大多数のサイトは厳密な構成証明ステートメントの検証を必要とせず、エンタープライズ用途以外では厳密な構成証明ステートメントの検証は非推奨とされていることから（
https://www.w3.org/TR/webauthn-1/#sctn-no-attestation-security-attestation[WebAuthn仕様書関連個所参照] ）、 WebAuthn4Jでは構成証明ステートメントの検証をしないように `AttestationStatementVerifier` と
`CertPathTrustworthinessVerifier` を構成した `WebAuthnManager` のインスタンスを返却する
`WebAuthnManager.createNonStrictWebAuthnManager` ファクトリメソッドを用意しています。

もし、エンタープライズなユースケースで、認証デバイスの厳密な検証が要件である場合は、
`WebAuthnManager` クラスのコンストラクタを用いて `AttestationStatementVerifier` と `CertPathTrustworthinessVerifier`
の実装をコンストラクタインジェクションして構成して下さい。

=== 構成証明ステートメントの検証

構成証明ステートメントの検証は、 `AttestationStatementVerifier` インタフェースの実装クラスが提供します。 構成照明ステートメント毎に、対応する実装クラスが提供されていますので、必要なVerifierからなるListを
`WebAuthnManager` クラスのコンストラクタに指定して下さい。 例えば、 `packed` のみをサポートする場合は、 `PackedAttestationStatementVerifier` を唯一の要素とするListとし、 例えば、 `packed`, `tpm` をサポートする場合は、 `PackedAttestationStatementVerifier` と `TPMAttestationStatementVerifier`
からなるListを指定して下さい。

==== 構成証明ステートメントの信頼性の検証

構成証明ステートメント自体の信頼性の検証は、証明書パスの検証、自己署名のパターンがありますが、 証明書パスの検証は `CertPathTrustworthinessVerifier` インタフェースの実装に検証が委譲されます。
WebAuthn4Jは `CertPathTrustworthinessVerifier` インタフェースの実装として `DefaultCertPathTrustworthinessVerifier` を提供しています。 `DefaultCertPathTrustworthinessVerifier` は `TrustAnchorRepository` インタフェースを通じて取得した `TrustAnchor` をトラストアンカーとして証明書パスの検証を行うことで構成証明ステートメントの信頼性の検証を行います。

==== トラストアンカーの解決

前節で `TrustAnchorRepository` インタフェースがトラストアンカーの取得に使用されると述べましたが、 `TrustAnchorRepository` インタフェースは `AAGUID` や `attestationCertificateKeyIdentifier` に基づいて `TrustAnchor` を返却するインタフェースです。
`webauthn4j-core` モジュールでは、 `TrustAnchorRepository` の実装として、`KeyStoreTrustAnchorRepository` を提供しています。
`KeyStoreTrustAnchorRepository` は、Java Key Storeファイルからトラストアンカーを取得します。なお、 `KeyStoreTrustAnchorRepository` は `AAGUID` や `attestationCertificateKeyIdentifier` に応じて異なる TrustAnchorを返却することはせず、
Java Key Storeファイルに登録された証明書を全てトラストアンカーとして扱います。

===== FIDO Metadata Serviceを用いたトラストアンカーの取得

WARNING: FIDO Metadata Statement関連の機能を提供する `webauthn4j-metadata` モジュールは実験的な提供段階です。

FIDO Allianceでは、FIDO Metadata Serviceという、認証デバイスのメタデータを配信するサービスを提供しています。
`webauthn4j-metadata` モジュールでは、`TrustAnchorRepository` の実装として `MetadataBLOBBasedTrustAnchorRepository` を提供しています。
`MetadataBLOBBasedTrustAnchorRepository` は `FidoMDS3MetadataBLOBProvider` と組み合わせることで
FIDO Metadata Serviceの公開する情報に基づいてトラストアンカーを構築することが可能です。

=== WebAuthn4Jが提供しない機能

WebAuthn4Jは特定のフレームワークに依存しないポータビリティを実現する為、 WebAuthnのAssertion/Attestationの検証に意図的に機能を絞り込んでおり、HTTPリクエストからのパラメータの取出、 Challengeの発行・セッションへの保存、カウンタ値の検証は具備していません。 使用する認証フレームワークに合わせて独自に実装して下さい。Spring Securityをご利用の場合は、 WebAuthn4J Spring Securityがそれらの認証フレームワーク特化の部分の実装を提供しますので活用をご検討下さい。

