[configuration]
== 設定

WebAuthn4Jを利用する上で中心となるクラスは2つ存在します。1つは登録時に資格情報を検証する
`WebAuthnRegistrationContextValidator` クラスで、もう1つは認証時に資格情報を検証する
`WebAuthnAuthenticationContextValidator` クラスです。
前者の `validate` メソッドは登録時のコンテキストを表現するWebAuthnRegistrationContextクラスを引数に持ち、
検証に成功した場合、`WebAuthnRegistrationContextValidationResponse` クラスを返却します。
後者の `validate` メソッドは認証時のコンテキストを表現するWebAuthnAuthenticationContextクラスを引数に持ち、
検証に成功した場合、`WebAuthnAuthenticationContextValidationResponse` クラスを返却します。
両者とも、検証に失敗した場合は、`ValidationException` クラスのサブクラスの例外をスローします。

`WebAuthnRegistrationContextValidator` は構成証明ステートメントの署名と信頼性の検証は、
それぞれ `AttestationStatementValidator` と `CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

厳密な構成証明ステートメントの検証を必要としないサイト向けに、`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した `WebAuthnRegistrationContextValidator` のインスタンスは、
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドで作成出来ます。

もし、エンタープライズなユースケースで、認証デバイスの厳密な検証が要件である場合は、
`WebAuthnRegistrationContextValidator` クラスのコンストラクタを用いて
`AttestationStatementValidator` と `CertPathTrustworthinessValidator` の実装をコンストラクタインジェクションして
構成して下さい。

==== 構成証明ステートメントの検証

構成証明ステートメントの検証は、 `AttestationStatementValidator` インタフェースの実装クラスが提供します。
構成照明ステートメント毎に、対応する実装クラスが提供されていますので、必要なValidatorからなるListを
`WebAuthnRegistrationContextValidator` クラスのコンストラクタに指定して下さい。
例えば、 `packed` のみをサポートする場合は、 `PackedAttestationStatementValidator` を唯一の要素とするListとし、
例えば、 `packed`, `tpm` をサポートする場合は、 `PackedAttestationStatementValidator` と `TPMAttestationStatementValidator`
からなるListを指定して下さい。

===== 構成証明ステートメントの信頼性の検証

構成証明ステートメント自体の信頼性の検証は、信頼するルート証明書から連なる証明書パスの検証、
ECDAAによる検証、自己署名のパターンがありますが、証明書パスの検証は `CertPathTrustworthinessValidator` インタフェースの実装
に検証を委ね、 ECDAAの場合は `ECDAATrustworthinessValidator` インタフェースの実装に検証が委譲されます。
WebAuthn4Jはいくつか `CertPathTrustworthinessValidator` インタフェースの実装を提供しており、
例えば `TrustAnchorCertPathTrustworthinessValidator` は `TrustAnchorResolver` インタフェースを通じて取得した
`TrustAnchor` をルート証明書として証明書パスの検証を行うことで構成証明ステートメントの信頼性の検証を行います。

==== サーバー側構成の表現

作成する資格情報のスコープを決定するrpIdなど、サーバー側の構成は `WebAuthnRegistrationContext` クラスの
フィールドである `ServerProperty` クラスによって表現されます。

==== 認証デバイスの表現

認証デバイスを表現するインタフェースとして、 `Authenticator` インタフェースが存在します。
登録時に、 `WebAuthnRegistrationContextValidationResponse` クラスが含む値を用いてAuthenticator インタフェースの
インスタンスを作成し、アプリケーションの作法に則り永続化してください。認証時の検証に必要となります。
なお、永続化する際は、credentialIdをキーに永続化すると良いでしょう。
`Authenticator` インタフェースの実装クラスを設計する際は、アプリケーションの要件に合わせて拡張すると良いでしょう。
典型的には、 `Authenticator` をユーザーが識別するためのfriendly nameの追加などが考えられるでしょう。



