[configuration]
== 設定

WebAuthn4Jを利用する上で中心となるクラスは2つ存在します。1つは登録時に資格情報を検証する
`WebAuthnRegistrationContextValidator` クラスで、もう1つは認証時に資格情報を検証する
`WebAuthnAuthenticationContextValidator` クラスです。
前者の `validate` メソッドは登録時のコンテキストを表現するWebAuthnRegistrationContextクラスを引数に持ち、
検証に成功した場合、`WebAuthnRegistrationContextValidationResponse` クラスを返却します。
後者の `validate` メソッドは認証時のコンテキストを表現するWebAuthnAuthenticationContextクラスを引数に持ち、
検証に成功した場合、`WebAuthnAuthenticationContextValidationResponse` クラスを返却します。
両者とも、検証に失敗した場合は、`ValidationException` クラスのサブクラスの例外をスローします。

`WebAuthnRegistrationContextValidator` は構成証明ステートメントの署名と信頼性の検証は、
それぞれ `AttestationStatementValidator` と `CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

厳密な構成証明ステートメントの検証を必要としないサイト向けに、`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した `WebAuthnRegistrationContextValidator` のインスタンスは、
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドで作成出来ます。

もし、エンタープライズなユースケースで、認証デバイスの厳密な検証が要件である場合は、
`WebAuthnRegistrationContextValidator` クラスのコンストラクタを用いて
`AttestationStatementValidator` と `CertPathTrustworthinessValidator` の実装をコンストラクタインジェクションして
構成して下さい。

==== 構成証明ステートメントの検証

構成証明ステートメントの検証

===== 構成証明ステートメントの信頼性の検証

構成証明ステートメント自体の信頼性の検証は、信頼するルート証明書から連なる証明書パスの検証、
ECDAAによる検証、自己署名のパターンがありますが、証明書パスの検証は `CertPathTrustworthinessValidator` インタフェースの実装
に検証を委ね、 ECDAAの場合は `ECDAATrustworthinessValidator` インタフェースの実装に検証が委譲されます。
WebAuthn4Jはいくつか `CertPathTrustworthinessValidator` インタフェースの実装を提供しており、
例えば `TrustAnchorCertPathTrustworthinessValidator` は `TrustAnchorResolver` インタフェースを通じて取得した
`TrustAnchor` をルート証明書として証明書パスの検証を行うことで構成証明ステートメントの信頼性の検証を行います。




==== 認証デバイス

認証デバイスは`Authenticator`インタフェースの実装として表現されます。
認証時に`Authenticator`インタフェースを実装したクラスが必要です。



==== RelyingPartyとしての構成

作成する資格情報のスコープを決定するrpIdなど、RelyingPartyとしての構成はServerPropertyクラスによって表現されます。







