[configuration]
== 設定

WebAuthn4Jを利用する上で中心となるクラスは2つ存在します。1つは登録時に資格情報を検証する
`WebAuthnRegistrationContextValidator` クラスで、もう1つは認証時に資格情報を検証する
`WebAuthnAuthenticationContextValidator` クラスです。

`WebAuthnRegistrationContextValidator` は構成証明ステートメントの署名と信頼性の検証は、
それぞれ `AttestationStatementValidator` と `CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

大多数のサイトは厳密な構成証明ステートメントの検証を必要としないでしょうから（
https://www.w3.org/TR/2019/PR-webauthn-20190117/#sctn-no-attestation-security-attestation[WebAuthn仕様書関連個所参照] ）、
WebAuthn4Jでは構成証明ステートメントの検証をしないように `AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した `WebAuthnRegistrationContextValidator` のインスタンスを返却する
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドを用意しています。

もし、エンタープライズなユースケースで、認証デバイスの厳密な検証が要件である場合は、
`WebAuthnRegistrationContextValidator` クラスのコンストラクタを用いて
`AttestationStatementValidator` と `CertPathTrustworthinessValidator` の実装をコンストラクタインジェクションして
構成して下さい。

=== 構成証明ステートメントの検証

構成証明ステートメントの検証は、 `AttestationStatementValidator` インタフェースの実装クラスが提供します。
構成照明ステートメント毎に、対応する実装クラスが提供されていますので、必要なValidatorからなるListを
`WebAuthnRegistrationContextValidator` クラスのコンストラクタに指定して下さい。
例えば、 `packed` のみをサポートする場合は、 `PackedAttestationStatementValidator` を唯一の要素とするListとし、
例えば、 `packed`, `tpm` をサポートする場合は、 `PackedAttestationStatementValidator` と `TPMAttestationStatementValidator`
からなるListを指定して下さい。

==== 構成証明ステートメントの信頼性の検証

構成証明ステートメント自体の信頼性の検証は、証明書パスの検証、ECDAAによる検証、自己署名のパターンがありますが、
証明書パスの検証は `CertPathTrustworthinessValidator` インタフェースの実装に検証を委ね、
ECDAAの場合は `ECDAATrustworthinessValidator` インタフェースの実装に検証が委譲されます。
WebAuthn4Jはいくつか `CertPathTrustworthinessValidator` インタフェースの実装を提供しており、
例えば `TrustAnchorCertPathTrustworthinessValidator` は `TrustAnchorResolver` インタフェースを通じて取得した
`TrustAnchor` をルート証明書として証明書パスの検証を行うことで構成証明ステートメントの信頼性の検証を行います。

===== FIDO Metadata Serviceを用いた構成証明ステートメントの信頼性の検証

FIDO Allianceでは、FIDO Metadata Serviceという、認証デバイスのメタデータを配信するサービスを提供しています。
このサービスを利用することにより、登録しようとしている認証デバイスで、セキュリティ上の問題が報告されていないか
チェックすることが可能です。FIDO Metadata Serviceを用いて構成証明ステートメントの信頼性の検証を行う場合、
`CertPathTrustworthinessValidator` の実装として `MetadataItemListCertPathTrustworthinessValidator` を使用して下さい。
`MetadataItemListCertPathTrustworthinessValidator` は `MetadataItemListResolver` インタフェースを通じて認証デバイスの
AAGUIDに対応する `MetadataItem` リストを解決しますので、 `MetadataItemListResolverImpl` と
`FidoMdsMetadataItemListProvider` を組み合わせて使うことで、FIDO Metadata Serviceによる信頼性の検証を行うことが可能です。

=== 認証デバイスの表現

認証デバイスを表現するインタフェースとして、 `Authenticator` インタフェースが存在します。
登録時に、 `WebAuthnRegistrationContextValidationResponse` クラスが含む値を用いて `Authenticator` インタフェースの
インスタンスを作成し、アプリケーションの作法に則り永続化してください。認証時の検証に必要となります。
なお、永続化する際は、検索する際の利便性を考え、credentialIdをキーに永続化すると良いでしょう。
`Authenticator` インタフェースの実装クラスを設計する際は、アプリケーションの要件に合わせて拡張すると良いでしょう。
典型的には、 `Authenticator` をユーザーが識別するための名前フィールドの追加などが考えられるでしょう。
