[configuration]
== 設定

=== アプリケーションへの組み込み

==== Maven依存関係

ライブラリとその依存関係を導入するために、以下をpom.xmlファイルに追加してください。

[source, xml]
----
<dependency>
	<groupId>net.sharplab.springframework.security.extensions</groupId>
	<artifactId>spring-security-webauthn-core</artifactId>
	<version>${version}</version>
</dependency>
----

==== Bean定義

==== Java Config


=== 認証デバイス登録時の検証

認証デバイス登録操作のハンドリングは、基本的にはアプリケーション側の責務であり、Spring Security WebAuthnは機能を直接提供することはしません。
但し、登録しようとしているデバイス情報が認証時に使用できるものであるか、検証する為に、WebAuthnRegistrationContextValidatorクラスを提供します。

=== 認証時の検証

==== 認証方法の選択

Spring Security WebAuthnでは、認証方法としてパスワード認証、パスワードと認証デバイスの組み合わせによる認証、
ユーザー検証をサポートした認証デバイスを単独での認証をサポートしています。
全ての認証方法をサポートし、ユーザーへの間口を広げることも出来ますし、認証デバイスを用いた認証だけに制限することで、
セキュリティを高めることも出来ます。

TODO:認証方法の選択設定方法

各ユーザーは、システムで許されている範囲で、認証方法を更に制限することが可能です。
例え、パスワード認証がシステム全体で許容されていたとしても、自分のアカウントのログインに関してはパスワード認証を
許容しないように設定することが可能です。

TODO:設定方法の紹介

=== ユーザーディレクトリとの統合



==== WebAuthnAuthenticatorServiceとWebAuthnAuthenticator

=== 公開鍵の有効範囲（RpId）設定

Web Authentication仕様では、公開鍵の取得時、その公開鍵の有効範囲を制限するためのパラメータとして、RpIdを指定します。
RpIdには、～ドメインを指定することが出来ます。例えば、～メソッドが実際に呼び出されたページのドメインが
"subdomain.example.com"だった場合に、RpIdを"subdomain.example.com"と指定すれば、
その公開鍵は"subdomain.example.com"とそのサブドメインの範囲だけで利用できますが、
RpIdを"example.com"とすることで、公開鍵が利用可能な範囲を"example.com"およびそのサブドメインに広げることが出来ます。


== クライアントサイドとのインタフェース仕様

=== 認証リクエストに期待するリクエストパラメーター

=== メタデータエンドポイント仕様

=== 認証デバイスの登録

=== 認証

== 高度なトピック

=== 多要素認証で第一要素認証のみ完了したユーザーの識別

Spring Security本体側のトピック？

=== メタデータ

=== チャレンジ

==== ChallengeAttrProcessor

Web Authentication仕様では、署名対象データにChallengeを含める必要があります。spring-security-webauthnでは、
Challengeをサーバーから渡すために、Challengeデータを含むMetaタグを出力するThymeleafのCustom Dialectを提供します。

==== ChallengeRepository

Challengeデータの生成を管理を行うインタフェースとして、ChallengeRepositoryインタフェースが定義されています。

=== 証言ステートメント信頼性の検証

Relying Partyとして証言ステートメントを検証する際、署名と信頼のそれぞれの検証が必要です。
Spring-Security-WebAuthnはそれぞれ、`AttestationStatementSignatureValidator`インタフェースの実装および
`AttestationStatementTrustWorthinessValidator`インタフェースの実装を用いて検証を行います。

===== 信頼の検証

証言ステートメントを証明書パスに基づいて検証する際、spring-security-webauthnは
`WebAuthnTrustAnchorService`インタフェースの実装を用いてトラスト・アンカーを取得します。
信頼の検証は、証言ステートメントが自己署名か、ECDAAか、それ以外かによって方法が異なり、
spring-security-webauthnではそれぞれの検証手段のインタフェースとして`SelfAttestationTrustworthinessValidator`インタフェース、
`ECDAATrustworthinessValidator`インタフェース、`CertPathTrustworthinessValidator`インタフェースを用意しています。
`WebAuthnTrustAnchorService`インタフェースの実装クラスは必要とする検証の内容に応じて、
`StrictAttestationStatementTrustworthinessValidator`と`LooseAttestationStatementTrustworthinessValidator`を用意していますが、
実際の検証は`SelfAttestationTrustworthinessValidator`インタフェース、
 `ECDAATrustworthinessValidator`インタフェース、`CertPathTrustworthinessValidator`インタフェースを実装したクラスに
委譲しています。

`FIDOMetadataServiceCertPathTrustworthinessValidator`は`CertPathTrustworthinessValidator`インタフェースを実装したクラスで、
FIDO Metadata Serviceで公開されている証明書をトラストアンカーに証言証明書の信頼を検証します。
更に、FIDO Metadata Serviceから得られた各証言証明書のStatus Reportを元に検証を行います。

===== `FIDOMetadataServiceCertPathTrustworthinessValidator`



===== `KeyStoreTrustAnchorService`

Java Key Storeファイルに保存した公開鍵証明書をトラストアンカーとして利用するための`WebAuthnTrustAnchorService`の
実装です。


==== 証言ステートメント署名の検証

spring-security-webauthnは`AttestationStatementSignatureValidator`インタフェースの実装として、
`FIDOU2FAttestationStatementSignatureValidator`と`WebAuthnAttestationStatementSignatureValidator`を提供します。
spring-security-webauthnは`AttestationStatementSignatureValidator`インタフェースを実装したクラスのBeanを自動で検出し、
署名の検証時、フォーマットと適合する`AttestationStatementSignatureValidator`を使用して検証を行います。


