[configuration]
== 設定

==== 構成証明ステートメントの検証

WebAuthn4Jでは、`WebAuthnRegistrationContextValidator` が認証デバイスの登録要求の検証を行いますが、
取得した構成証明ステートメントの署名と信頼性の検証は、それぞれ `AttestationStatementValidator` と
`CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

厳密な構成証明ステートメントの検証を必要としないサイト向けに、`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した `WebAuthnRegistrationContextValidator` のインスタンスは、
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドで作成出来ます。


===== 構成証明ステートメントの信頼性の検証

信頼の検証は、構成証明ステートメントが自己署名か、ECDAAか、それ以外かによって方法が異なり、
Spring Security WebAuthnではそれぞれの検証手段のインタフェースとして `SelfAttestationTrustworthinessValidator` 、
`ECDAATrustworthinessValidator` 、 `CertPathTrustworthinessValidator` を用意しています。

`CertPathTrustworthinessValidator` が証明書パスに基づいて構成証明ステートメントを検証する際、WebAuthn4Jは
`TrustAnchorProvider` インタフェースの実装を用いてトラスト・アンカーを取得します。

===== FIDOMetadataServiceCertPathTrustworthinessValidator

`FIDOMetadataServiceCertPathTrustworthinessValidator` は `CertPathTrustworthinessValidator` インタフェースを実装した
クラスで、FIDO Metadata Serviceで公開されている証明書をトラストアンカーに構成証明証明書の信頼を検証します。
更に、FIDO Metadata Serviceから得られた各構成証明証明書のStatus Reportを元に検証を行います。


==== 認証デバイス

認証デバイスは`Authenticator`インタフェースの実装として表現されます。
認証時に`Authenticator`インタフェースを実装したクラスが必要です。



==== RelyingPartyとしての構成

作成する資格情報のスコープを決定するrpIdなど、RelyingPartyとしての構成はServerPropertyクラスによって表現されます。





=== ログ

WebAuthn4JはSLF4Jをログインタフェースライブラリとして使用します。
Logbackなどログ実装ライブラリを構成し、ログをお好みのスタイルで出力してください。


