[deep-dive]
== 詳細

=== Project Modules

WebAuthn4Jは、以下の4つのModuleから構成されます。

==== Core webauthn4j-core.jar

Attestation/Assertionの検証に関わるコア機能を提供します。

==== Extras webauthn4j-extras.jar

FIDO Metadata Serviceを用いたTrustAnchorの解決など、追加的な機能を提供します。

==== Test webauthn4j-test.jar

WebAuthn4Jのテストを行うための内部ライブラリです。含まれているクラスは、Publicであっても、セマンティックバージョニングに従わずに
設計変更されることがあります。

==== Util webauthn4j-util.jar

WebAuthn4Jライブラリで使用されるユーティリティクラスをまとめたライブラリです。

=== Request/Response

`com.webauthn4j.request` , `com.webauthn4j.request` パッケージ配下のクラスはイミュータブルなDTOとして設計されています。

=== Converter, Registry

リクエスト、レスポンスパッケージ配下のクラスはJacksonによってシリアライズ、デシリアライズ可能なように設計されています。
一部のクラスはカスタムなシリアライザ、デシリアライザが必要であり、 `converter` パッケージ配下に集約されています。
カスタムシリアライザ、デシリアライザは `WebAuthnModule` にまとめられており、 `WebAuthnModule` が適用された
`ObjectMapper` インスタンスは `Registry` クラスに登録され、WebAuthn4Jの各クラス間で共有されています。
もしカスタムなシリアライザ、デシリアライザの追加登録が必要な場合は、Registryクラスが保持するObjectMapperに登録しましょう。

=== Validator

資格情報の登録時のバリデーター

`WebAuthnRegistrationContextValidator`

資格情報の認証時のバリデーター

`WebAuthnAuthenticationContextValidator`

=== 例外クラス

検証に失敗した場合、 `ValidationException` のサブクラスがスローされます。


=== ログ

WebAuthn4JはSLF4Jをログインタフェースライブラリとして使用します。
Logbackなどログ実装ライブラリを構成し、ログをお好みのスタイルで出力してください。
