== 詳細

=== Project Modules

WebAuthn4Jは、以下の4つのModuleから構成されます。

==== Core webauthn4j-core.jar

Attestation/Assertionの検証に関わるコア機能を提供します。

==== Metadata webauthn4j-metadata.jar

FIDO Metadata Serviceを用いたTrustAnchorの解決など、追加的な機能を提供します。

==== Test webauthn4j-test.jar

WebAuthn4Jのテストを行うための内部ライブラリです。含まれているクラスは、Publicであっても、セマンティックバージョニングに従わずに
設計変更されることがあります。

==== Util webauthn4j-util.jar

WebAuthn4Jライブラリで使用されるユーティリティクラスをまとめたライブラリです。

=== クラス

==== Data transfer Objects

`com.webauthn4j.data` パッケージ配下のクラスはイミュータブルなDTOとして設計されています。

==== Converter, WebAuthnModule

データパッケージ配下のクラスはJacksonによってシリアライズ、デシリアライズ可能なように設計されています。
一部のクラスはカスタムなシリアライザ、デシリアライザが必要であり、 `converter` パッケージ配下に集約されています。
カスタムシリアライザ、デシリアライザは `WebAuthnJSONModule` と `WebAuthnCBORModule` というJacksonのModuleにまとめられています。
WebAuthn4JのValidatorは内部で使用するJacksonの `ObjectMapper` に自動で `WebAuthnModule` を適用しますが、Validatorの外部で
WebAuthn4Jのシリアライザ、デシリアライザを使用したい場合は、Jacksonの `ObjectMapper` に `WebAuthnModule` を登録すると
良いでしょう。もしWebAuthn4JのValidatorでカスタムなシリアライザ、デシリアライザを使用したい場合は、WebAuthn4JのValidator
のコンストラクタに、カスタムなシリアライザ、デシリアライザを登録したObjectMapperを渡すことで使用可能です。

==== TrustAnchorsResolver

`TrustAnchorsResolver` インタフェースは `TrustAnchorCertPathTrustworthinessValidator` で構成証明ステートメントの信頼性の
検証を行う際に信頼するルート証明書のセットを探索するために使用されます。

==== TrustAnchorsProvider

`TrustAnchorsProvider` インタフェースは前述の `TrustAnchorsResolver` インタフェースの実装である `TrustAnchorsResolverImpl`
がTrustAnchorの読込処理を委譲する先のインタフェースです。実装としてJava Key StoreファイルからTrustAnchorを読み込む
`KeyStoreFileTrustAnchorsProvider` クラスが提供されている他、Spring Security WebAuthnでは、SpringのResourceから
TrustAnchorを読み込む `CertFileResourcesTrustAnchorProvider` が提供されています。


==== 例外クラス

検証に失敗した場合、 `ValidationException` のサブクラスがスローされます。


=== ログ

WebAuthn4JはSLF4Jをログインタフェースライブラリとして使用します。
Logbackなどログ実装ライブラリを構成し、ログをお好みのスタイルで出力してください。

