== FAQ

=== `PublicKeyCredentialCreationOptions` の `excludeCredentials` に何を指定すべきか

`PublicKeyCredentialCreationOptions` の `excludeCredentials` は登録時に除外したい Authenticator を指定するためのパラメータです。
アカウントに既に紐付いている Authenticator を新規登録から除外する際に使用します。

[source,java]
----
// 除外する Authenticator がない場合
List<PublicKeyCredentialDescriptor> excludeCredentials = null;

// 特定の Authenticator を除外する場合
List<PublicKeyCredentialDescriptor> excludeCredentials = Collections.singletonList(
    new PublicKeyCredentialDescriptor(
        PublicKeyCredentialType.PUBLIC_KEY,
        existingCredentialId,
        transports
    )
);
----

* nullを指定した場合、除外される Authenticator はありません
* そのユーザーがすでに持っている認証器を excludeCredentials に指定することで、誤って同じ認証器を再登録することを防止できます


=== `PublicKeyCredentialRequestOptions` の `allowCredentials` に何を指定すべきか

PublicKeyCredentialRequestOptions の allowCredentials は認証時に使用可能な Authenticator を指定するためのパラメータです。
non-discoverable credentialの場合、allowCredentialsにcredentialIdを指定する必要があります。

[source,java]
----
// 全てのAuthenticatorを許可する場合
List<PublicKeyCredentialDescriptor> allowCredentials = null;

// 特定のAuthenticatorのみを許可する場合
List<PublicKeyCredentialDescriptor> allowCredentials = Collections.singletonList(
    new PublicKeyCredentialDescriptor(
        PublicKeyCredentialType.PUBLIC_KEY,
        credentialId,
        transports
    )
);
----

=== `WebAuthnManager` クラス、責務が多すぎでは？

Q: `WebAuthnManager` は、登録処理と認証処理という異なる2つの機能を提供しており、
認証処理だけを必要とするクラスから呼び出す場合も、`WebAuthnManager` のインスタンス化時に登録処理だけで必要なAttestation関連の設定が必要であり、不便です。

A: `WebAuthnManager` を分割した `WebAuthnRegistrationManager` と `WebAuthnAuthenticationManager` を提供していますのでそちらをご利用下さい。

