[introduction]
== 導入

=== Web Authenticationとは

Web Authenticationは、W3Cで仕様策定が進められている、Webアプリケーションの新しいセキュアな認証方式仕様です。
ローカル認証や公開鍵認証、Origin別の鍵管理を組み合わせることで、フィッシングなど認証プロセスに対する攻撃に対して堅固な認証を実現しています。
主要ブラウザでの実装が進みつつあり、セキュリティ、利便性を重視するユーザーに対して優れた選択肢を提供します。
当初はFIDO AllianceでFIDO2.0の一部として仕様策定が進められていましたが、現在はW3Cに移管され、仕様策定が行われています。

=== WebAuthn4Jとは

Web Authentication仕様に基づくサーバーサイド検証を行うためのポータブルなJavaライブラリです。
元々はSpring Security WebAuthnの一部として開発を進めていましたが、より多くのアプリケーションに対してWeb Authentication仕様に
基づく認証機能を提供するためにSpring Security WebAuthnからアサーションの検証に関するコアを切り出して依存関係を最小化しました。

=== 特徴

==== サポートする証言ステートメントフォーマット

Spring Security WebAuthnが現在サポートする証言ステートメントフォーマットは以下の通りです。

- Packed attestation
- FIDO U2F attestation
- Android Key attestation
- Android SafetyNet attestation
- TPM attestation
- None attestation

==== 準拠状況

https://fidoalliance.org/certification/functional-certification/conformance/[FIDO Allianceが提供するFIDO2 Test Tools]
で必須のテストケースに加え、オプションのAndroid Key attestationのテストケースを全て合格しています。

NOTE: WebAuthn4Jを利用して開発されているSpring Security WebAuthnがFIDO Serverインタフェースを提供しており、
Spring Security WebAuthnのFIDO Serverインタフェースに対してFIDO2 test toolsを実行して検証を行っています。

==== ポータビリティ

WebAuthn4JはSLF4JとJacksonにのみ依存しており、非常に高いポータビリティを持っています。
あなたのJavaアプリへの導入の障害は殆どないでしょう。

=== 要件

==== 言語

- Java8以降

=== 動作環境

- SecureContext（サイトがHTTPS接続か、localhost）

=== Maven Centralからの取得
Mavenを使用している場合、webauthn4jを依存関係として追加して使用してください：

```
<properties>
  ...
  <!-- Use the latest version whenever possible. -->
  <webauthn4j.version>0.6.6.RELEASE</webauthn4j.version>
  ...
</properties>

<dependencies>
  ...
  <dependency>
    <groupId>com.webauthn4j</groupId>
    <artifactId>webauthn4j-core</artifactId>
    <version>${webauthn4j.version}</version>
  </dependency>
  ...
</dependencies>
```

=== ソースコード

ソースコードは https://github.com/webauthn4j/webauthn4j[Github] で管理されています。
----
git clone git@github.com:webauthn4j/webauthn4j.git
----

=== ライセンス

WebAuthn4jは http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license] ライセンスの
オープンソースソフトウェアです。

=== 開発への参加

WebAuthn4Jに興味を持って頂きありがとうございます。WebAuthn4Jの開発に参加するには、必ずしも開発者である必要はありません。
ドキュメンテーションに関する協力者も必要としています。　開発への参加も、勿論歓迎です。
お気軽にIssueやPull Requestをお寄せ下さい。
