[quick-start]
== クイックスタート

WebAuthn認証では、前もって認証デバイスで生成した公開鍵をサーバーに登録し、認証時に認証デバイスで生成した
署名を公開鍵で検証することで認証が成立する認証方式です。登録時にサーバーに送信される公開鍵やデバイスの構成情報を
含むデータは構成証明（Attestation）と呼ばれ、認証時にサーバーに送信される署名を含んだデータは認証証明（Assertion）と呼ばれます。

=== 構成証明の検証

認証デバイスの登録時に構成証明を検証するためには、 `WebAuthnRegistrationContextValidator#validate` を呼び出します。
呼び出す際は、 `WebAuthnRegistrationContext` のインスタンスを引数に指定する必要があります。
`WebAuthnRegistrationContext` のコンストラクタの引数に指定する、 `clientDataJSON` と `attestationObject` はフロントエンド側で
WebAuthn JS APIを実行して取得した値となります。何らかの方法でフロントエンド側からサーバー側に伝送し、指定してください。
第三パラメータの `serverProperty` はサーバー側から取得する値をまとめたパラメータです。 `ServerProperty` のコンストラクタを
呼び出す際のパラメータには以下の値を指定して下さい。
`origin` にはWebAuthnによる認証を提供するサイトのOriginを指定して下さい。WebAuthnでは、ブラウザがブラウザが認識しているOriginを
ClientDataに書き込んで署名を行います。WebAuthn4Jは書き込まれたOriginが指定されたOriginと合致するかを検証します。
`rpId` にはWebAuthnによる認証を提供するサイトのrpIdを指定して下さい。rpIdは資格情報のスコープを指定するパラメータです。
詳しくは https://www.w3.org/TR/2019/PR-webauthn-20190117/#relying-party-identifier[WebAuthnの仕様書] を参照して下さい。
`challenge` はリプレイ攻撃を防ぐ為のパラメータです。サーバー側で `challenge` としてランダムなバイト列を生成し、
フロントエンド側でWebAuthn JS APIを実行する際にパラメータとして指定して署名対象に含め、サーバー側で値の一致を検証することで
リプレイ攻撃から防御することが出来ます。
`challenge` には発行したChallengeを指定して下さい。発行したChallengeを検証時まで永続化しておくのはアプリケーション側の責務です。
セッションなどに格納しておくと良いでしょう。
`tokenBindingId` はToken bindingを利用する場合のパラメータです。利用しない場合は `null` を指定してください。
`userVerificationRequired` は認証デバイスでのユーザーの本人性確認が必要かどうかを示すパラメータです。
検証に失敗した場合は、 `ValidationException` のサブクラスがthrowされます。
検証後の資格情報のデータベース等への永続化自体はWebAuthn4Jのスコープ外であり、アプリケーション側の責務となります。

```java
// Client properties
byte[] clientDataJSON    = null /* set clientDataJSON */;
byte[] attestationObject = null /* set attestationObject */;

// Server properties
Origin origin          = null /* set origin */;
String rpId            = null /* set rpId */;
Challenge challenge    = null /* set challenge */;
byte[] tokenBindingId  = null /* set tokenBindingId */;
ServerProperty serverProperty = new ServerProperty(origin, rpId, challenge, tokenBindingId);

WebAuthnRegistrationContext registrationContext = new WebAuthnRegistrationContext(clientDataJSON, attestationObject, serverProperty, false);

// WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator() は 構成証明ステートメントを
// 検証しないWebAuthnRegistrationContextValidator インスタンスを返却します。これは大多数のWebアプリケーションに推奨の構成です。
// エンタープライズ用途のWebアプリケーションで構成証明ステートメントの検証が必要な場合はWebAuthnRegistrationContextValidatorの
// コンストラクタを使用し、使いたいvalidatorを指定してください
WebAuthnRegistrationContextValidator webAuthnRegistrationContextValidator =
        WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator();


WebAuthnRegistrationContextValidationResponse response = webAuthnRegistrationContextValidator.validate(registrationContext);

// アプリケーションの作法に則り、Authenticatorオブジェクトを永続化してください。認証時に使用されます。
Authenticator authenticator =
        new AuthenticatorImpl( // You may create your own Authenticator implementation to save friendly authenticator name
                response.getAttestationObject().getAuthenticatorData().getAttestedCredentialData(),
                response.getAttestationObject().getAttestationStatement(),
                response.getAttestationObject().getAuthenticatorData().getSignCount()
        );
save(authenticator); // アプリケーションの作法に則った、Authenticatorオブジェクトの永続化

```

=== 認証証明の検証

認証時に認証証明を検証するためには、 `WebAuthnAuthenticationContextValidator#validate` を呼び出します。
呼び出す際は、 `WebAuthnAuthenticationContext` と `Authenticator` のインスタンスを引数に指定する必要があります。
`WebAuthnAuthenticationContext` のコンストラクタの引数に指定する、 `credentialId` と `clientDataJSON` 、
`authenticatorData` 、 `signature` はフロントエンド側でWebAuthn JS APIを実行して取得した値となります。
何らかの方法でフロントエンド側からサーバー側に伝送し、指定してください。
`serverProperty` はサーバー側から取得する値をまとめたパラメータです。
`userVerificationRequired` は認証デバイスでのユーザーの本人性確認が必要かどうかを示すパラメータです。
タッチボタンのみを備え、認証における「所持」要素のみを提供する認証デバイスとパスワードを組み合わせて
多要素認証を実現する場合は `false` で良いでしょうし、認証デバイスによる本人性確認＋「所持」による多要素認証を行う場合は
`true` を指定する必要があります。
検証に失敗した場合は、 `ValidationException` のサブクラスがthrowされます。
検証に成功した場合、認証デバイスに紐づけたカウンタの値を更新してください。カウンタは万が一認証デバイスのクローンが
作成された場合を検知するために用意されています。カウンタについて詳しくは
https://www.w3.org/TR/2019/PR-webauthn-20190117/#sign-counter[WebAuthnの仕様書] を参照して下さい。

```java
// Client properties
byte[] credentialId      = null /* set credentialId */;
byte[] clientDataJSON    = null /* set clientDataJSON */;
byte[] authenticatorData = null /* set authenticatorData */;
byte[] signature = null /* set signature */;

// Server properties
Origin origin          = null /* set origin */;
String rpId            = null /* set rpId */;
Challenge challenge    = null /* set challenge */;
byte[] tokenBindingId  = null /* set tokenBindingId */;
ServerProperty serverProperty = new ServerProperty(origin, rpId, challenge, tokenBindingId);

WebAuthnAuthenticationContext authenticationContext =
        new WebAuthnAuthenticationContext(
                credentialId,
                clientDataJSON,
                authenticatorData,
                signature,
                serverProperty,
                true
        );

Authenticator authenticator = load(); // 登録時に永続化したauthenticatorオブジェクトを読込

WebAuthnAuthenticationContextValidator webAuthnAuthenticationContextValidator =
        new WebAuthnAuthenticationContextValidator();

WebAuthnAuthenticationContextValidationResponse response = webAuthnAuthenticationContextValidator.validate(authenticationContext, authenticator);

// authenticatorのカウンタを更新
updateCounter(
        response.getAuthenticatorData().getAttestedCredentialData().getCredentialId(),
        response.getAuthenticatorData().getSignCount()
);
```

